#!/bin/sh -e

# EDIT these variables
# the hostname (or IP address) of your philips hue bridge
huehostname=001788af30f0
# see https://developers.meethue.com/develop/get-started-2/ to create an apikey
hueapikey=PuTyOuRaPiKeYhErE123456789
# the device ID for your philips hue smart plug
# use http://$huehostname/api/$hueapikey/lights/ to see the ID for all devices
huelightid=9

# no need to edit these variables
tftpdir=/var/lib/tftpboot
arch=arm64
compiler=aarch64-linux-gnu-
image=arch/arm64/boot/Image

if [ -z "$1" ]; then
	echo "while standing in your kernel directory:"
	echo ""
	echo "usage: build_boot [-n] <board>"
	exit
fi

if [ ! -e ".git" ]; then
	echo "you are not standing in a git tree or a git worktree"
	exit
fi

if [ ! -w "$tftpdir" ]; then
	echo "please make sure that you have write permission to: $tftpdir"
	exit
fi

if [ "$1" == -n ]; then
	power=0
	board=$2
else
	power=1
	board=$1
fi

case $board in
	rock5b*)
		;;
	*)
		echo "board: $board is not defined"
		exit
esac

ARCH=$arch CROSS_COMPILE=$compiler make -j$(nproc)

cp $image $tftpdir/

rm -rf tmp-modules/lib/modules/*
ARCH=$arch CROSS_COMPILE=$compiler make -j$(nproc) -s modules_install INSTALL_MOD_PATH=tmp-modules INSTALL_MOD_STRIP=1

case $board in
	rock5b-ep*)
		cp arch/arm64/boot/dts/rockchip/rk3588-rock-5b.dtb $tftpdir/
		cp arch/arm64/boot/dts/rockchip/rk3588-rock-5b-pcie-ep.dtbo $tftpdir/
		NFS_DIR=/srv/nfs/rootfs_ep
		rm -rf $NFS_DIR/lib/modules/*
		cp -r tmp-modules/lib/modules/* $NFS_DIR/lib/modules/
		;;
	rock5b-rc*)
		cp arch/arm64/boot/dts/rockchip/rk3588-rock-5b.dtb $tftpdir/
		cp arch/arm64/boot/dts/rockchip/rk3588-rock-5b-pcie-srns.dtbo $tftpdir/
		NFS_DIR=/srv/nfs/rootfs_rc
		rm -rf $NFS_DIR/lib/modules/*
		cp -r tmp-modules/lib/modules/* $NFS_DIR/lib/modules/
		;;
	rock5b*)
		# COMMON
		cp arch/arm64/boot/dts/rockchip/rk3588-rock-5b.dtb $tftpdir/
		# EP
		cp arch/arm64/boot/dts/rockchip/rk3588-rock-5b-pcie-ep.dtbo $tftpdir/
		NFS_DIR=/srv/nfs/rootfs_ep
		rm -rf $NFS_DIR/lib/modules/*
		cp -r tmp-modules/lib/modules/* $NFS_DIR/lib/modules/
		# RC
		cp arch/arm64/boot/dts/rockchip/rk3588-rock-5b-pcie-srns.dtbo $tftpdir/
		NFS_DIR=/srv/nfs/rootfs_rc
		rm -rf $NFS_DIR/lib/modules/*
		cp -r tmp-modules/lib/modules/* $NFS_DIR/lib/modules/
		;;
esac

if [ $power == 1 ]; then
	curl --no-progress-meter -X PUT -d '{"on":false}' http://$huehostname/api/$hueapikey/lights/$huelightid/state > /dev/null
	sleep 5
	curl --no-progress-meter -X PUT -d '{"on":true}' http://$huehostname/api/$hueapikey/lights/$huelightid/state > /dev/null
fi
